# Параметры для разбиения данных
preprocess:
  test_size: 0.2  # 20% данных будут использованы для тестирования
  random_state: 42

# Параметры модели
# Параметры для модели
model:
  n_estimators_values: [50, 100, 150, 200]  # Разные значения для n_estimators
  max_depth: 10  # Максимальная глубина деревьев
  seed: 42  # Начальное состояние генератора случайных чисел

